In [1]:
# Question 1
# Create a numpy array with 10 elements of the shape(10,1) using np.random and 
# find out the mean of the elements using basic numpy functions.

import numpy as np

x = np.random.random((10,1))
print(x)

[[0.36049539]
 [0.50345145]
 [0.25812315]
 [0.24368974]
 [0.91697032]
 [0.74724101]
 [0.96051892]
 [0.58521745]
 [0.19322053]
 [0.05055124]]


In [2]:
x.shape

(10, 1)

In [3]:
np.mean(x)

0.4819479205034397

In [4]:
# Question 2
# Create a numpy array with 20 elements of the shape(20,1) using np.random 
# find the variance and standard deviation of the elements.

y = np.random.random((20,1))
y

array([[0.62192987],
       [0.84692863],
       [0.38395476],
       [0.82724518],
       [0.59657136],
       [0.98706388],
       [0.02109479],
       [0.6913901 ],
       [0.42530265],
       [0.11715492],
       [0.38196806],
       [0.8966226 ],
       [0.30452524],
       [0.64815622],
       [0.07865493],
       [0.8695722 ],
       [0.57742653],
       [0.37974538],
       [0.82166909],
       [0.36944023]])

In [5]:
y.shape

(20, 1)

In [6]:
print("Standard Deviation of array is",np.std(y))

print("Varidance of array is",np.var(y))

Standard Deviation of array is 0.2802801056737303
Varidance of array is 0.07855693763647743


In [7]:

# Question 3
# Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random. 
# Print the matrix which is the matrix multiplication of A and B. 
# The shape of the new matrix should be (10,25). 
# Using basic numpy math functions only find the sum of all the elements of the new matrix.

A = np.random.random((10,20))
A

array([[0.67408755, 0.47246986, 0.4758441 , 0.2277576 , 0.98102152,
        0.57729977, 0.88807555, 0.11385807, 0.29854478, 0.75109283,
        0.92707988, 0.51254726, 0.52646659, 0.58005158, 0.94081536,
        0.37874852, 0.92861176, 0.47638997, 0.48910603, 0.46619693],
       [0.05363084, 0.45258396, 0.00570936, 0.15221943, 0.16079498,
        0.52446502, 0.55051414, 0.04830388, 0.29785625, 0.9894961 ,
        0.20880254, 0.34768996, 0.66230881, 0.87851978, 0.87208527,
        0.75205959, 0.50380383, 0.71844592, 0.56870774, 0.60046395],
       [0.31856534, 0.34492876, 0.69719946, 0.18075673, 0.6437323 ,
        0.3543718 , 0.24573802, 0.02064155, 0.7514747 , 0.32144515,
        0.39101185, 0.13101573, 0.57207773, 0.04777958, 0.7678603 ,
        0.88215215, 0.09977859, 0.71562568, 0.58894378, 0.02492806],
       [0.81669639, 0.03258477, 0.58701465, 0.07173233, 0.58181978,
        0.41399712, 0.29420706, 0.69866737, 0.73804709, 0.06402808,
        0.63315039, 0.62790672, 0.19852941, 0

In [8]:
B = np.random.random((20,25))
B

array([[0.12888569, 0.40918919, 0.54002425, 0.66492568, 0.37235362,
        0.80198669, 0.17954884, 0.14298624, 0.66724166, 0.17143094,
        0.31930033, 0.0994691 , 0.30803748, 0.21319017, 0.67620102,
        0.95732277, 0.837728  , 0.62586079, 0.8294343 , 0.38848362,
        0.64996298, 0.77682652, 0.51290089, 0.64028511, 0.82721335],
       [0.24798429, 0.08453541, 0.53812963, 0.36391325, 0.53937931,
        0.82453899, 0.86711103, 0.88417237, 0.26087336, 0.44213361,
        0.56384747, 0.41720841, 0.44340565, 0.85104538, 0.60745954,
        0.70267532, 0.63122861, 0.77234961, 0.3285913 , 0.12247309,
        0.04741543, 0.03612461, 0.65799925, 0.28004397, 0.86979489],
       [0.43348171, 0.76832355, 0.17799296, 0.27930604, 0.97229548,
        0.13836988, 0.63079896, 0.05111527, 0.98077461, 0.8104477 ,
        0.83238112, 0.62319195, 0.94832951, 0.04535176, 0.64812963,
        0.77506527, 0.51846286, 0.72139272, 0.35914093, 0.99231311,
        0.94294387, 0.53015419, 0.00660981, 0.

In [9]:
New = np.matmul(A,B)
New

array([[6.68371311, 5.1090359 , 6.3848671 , 6.8628987 , 6.86887064,
        7.70638748, 5.48195248, 5.80196551, 7.57687023, 6.13157957,
        5.15744485, 5.24714177, 6.15119493, 6.30137533, 7.09672582,
        6.43716273, 7.06231232, 6.57041528, 6.04683224, 6.02800468,
        7.35371617, 5.95854001, 5.44411423, 6.64186675, 6.77849526],
       [5.57071028, 3.8053612 , 5.18863576, 5.12065036, 5.95835454,
        6.16505377, 5.1506216 , 4.98483028, 6.00968   , 4.81460636,
        3.81270995, 4.08330056, 5.51392179, 5.29169484, 5.60941296,
        5.43639577, 5.56301543, 4.73013574, 4.85397954, 4.72310692,
        5.75835394, 4.30543658, 4.62976983, 4.97620461, 4.98779714],
       [4.3128158 , 4.21104567, 4.53220536, 4.08929586, 4.81794023,
        5.1816199 , 4.59267929, 3.72634779, 5.1823941 , 4.69492186,
        3.58831747, 3.32713986, 4.5811471 , 4.1759986 , 5.13049599,
        4.5221896 , 5.0807165 , 4.65808826, 3.75955682, 4.4400436 ,
        5.25277177, 3.8462914 , 3.00564611, 4.

In [10]:
New.shape

(10, 25)

In [11]:

New.sum()

1292.663933499039

In [12]:

a = np.random.rand(10,1)

In [13]:
a = list((map( lambda x:1 / (1 + np.exp(-x) ), a ) ) )

In [14]:

a = np.array(a)
a

array([[0.71609125],
       [0.58706058],
       [0.56071075],
       [0.66999613],
       [0.51502727],
       [0.62919288],
       [0.51875026],
       [0.67146271],
       [0.50974528],
       [0.58639545]])