# Question 2

In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
x = iris.data
y = iris.target

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.20,random_state = 0)

# Use GaussianNB and print the following:
### i. Confusion matrix <br>  ii. Classification report

In [5]:
from sklearn.naive_bayes import GaussianNB

In [6]:
classifier = GaussianNB()

In [7]:
classifier.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [8]:
y_pred = classifier.predict(x_test)

In [9]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test, y_pred))

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]


In [10]:
metrics.classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        11\n           1       0.93      1.00      0.96        13\n           2       1.00      0.83      0.91         6\n\n   micro avg       0.97      0.97      0.97        30\n   macro avg       0.98      0.94      0.96        30\nweighted avg       0.97      0.97      0.97        30\n'

# Use MultinomialNB and print the following:
### i. Confusion matrix <br>  ii. Classification report

In [11]:
from sklearn.naive_bayes import MultinomialNB
cl = MultinomialNB()
cl.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [12]:
y_pred = cl.predict(x_test)

In [13]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test, y_pred))

[[11  0  0]
 [ 0  0 13]
 [ 0  0  6]]


In [14]:
metrics.classification_report(y_test,y_pred)

c:\users\prateek\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        11\n           1       0.00      0.00      0.00        13\n           2       0.32      1.00      0.48         6\n\n   micro avg       0.57      0.57      0.57        30\n   macro avg       0.44      0.67      0.49        30\nweighted avg       0.43      0.57      0.46        30\n'